// Generated by gencpp from file om_modbus_master/om_response.msg
// DO NOT EDIT!


#ifndef OM_MODBUS_MASTER_MESSAGE_OM_RESPONSE_H
#define OM_MODBUS_MASTER_MESSAGE_OM_RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace om_modbus_master
{
template <class ContainerAllocator>
struct om_response_
{
  typedef om_response_<ContainerAllocator> Type;

  om_response_()
    : data()
    , slave_id(0)
    , func_code(0)  {
      data.assign(0);
  }
  om_response_(const ContainerAllocator& _alloc)
    : data()
    , slave_id(0)
    , func_code(0)  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<int32_t, 32>  _data_type;
  _data_type data;

   typedef int8_t _slave_id_type;
  _slave_id_type slave_id;

   typedef int8_t _func_code_type;
  _func_code_type func_code;





  typedef boost::shared_ptr< ::om_modbus_master::om_response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::om_modbus_master::om_response_<ContainerAllocator> const> ConstPtr;

}; // struct om_response_

typedef ::om_modbus_master::om_response_<std::allocator<void> > om_response;

typedef boost::shared_ptr< ::om_modbus_master::om_response > om_responsePtr;
typedef boost::shared_ptr< ::om_modbus_master::om_response const> om_responseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::om_modbus_master::om_response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::om_modbus_master::om_response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::om_modbus_master::om_response_<ContainerAllocator1> & lhs, const ::om_modbus_master::om_response_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.slave_id == rhs.slave_id &&
    lhs.func_code == rhs.func_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::om_modbus_master::om_response_<ContainerAllocator1> & lhs, const ::om_modbus_master::om_response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace om_modbus_master

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::om_modbus_master::om_response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::om_modbus_master::om_response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om_modbus_master::om_response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::om_modbus_master::om_response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om_modbus_master::om_response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::om_modbus_master::om_response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::om_modbus_master::om_response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b0532e32896a8d6752324b9d943fe9e";
  }

  static const char* value(const ::om_modbus_master::om_response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b0532e32896a8d6ULL;
  static const uint64_t static_value2 = 0x752324b9d943fe9eULL;
};

template<class ContainerAllocator>
struct DataType< ::om_modbus_master::om_response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "om_modbus_master/om_response";
  }

  static const char* value(const ::om_modbus_master::om_response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::om_modbus_master::om_response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[32] data\n"
"int8 slave_id\n"
"int8 func_code\n"
"\n"
;
  }

  static const char* value(const ::om_modbus_master::om_response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::om_modbus_master::om_response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.slave_id);
      stream.next(m.func_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct om_response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::om_modbus_master::om_response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::om_modbus_master::om_response_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "slave_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.slave_id);
    s << indent << "func_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.func_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OM_MODBUS_MASTER_MESSAGE_OM_RESPONSE_H
